Cherry-pick based on commit message

diff --git a/.github/workflows/update-dev.yaml b/.github/workflows/update-dev.yaml
--- a/.github/workflows/update-dev.yaml
+++ b/.github/workflows/update-dev.yaml
@@ -82,7 +82,18 @@ jobs:
 
     - name: Cherry-pick dev commits onto dev-new
       run: |
-        diverged_commits=$(git log --pretty=format:"%H" --reverse upstream/master-ci..origin/dev | tail -n +4)
+        commit_hash=$(git log --pretty=format:"%H %s" | grep -E 'openpilot v[0-9]+\.[0-9]+\.[0-9]+ release' | head -n 1 | cut -d ' ' -f 1)
+        # Get all commit hashes after and including the found commit hash
+        if [ -n "$commit_hash" ]; then
+          diverged_commits=$(git log --pretty=format:"%H" --reverse $commit_hash..opgm/dev | tail -n +3)
+          echo "Will cherry-pick the following commits:"
+          for commit in $diverged_commits; do
+            echo "  $commit : $(git log -1 --pretty=format:"%s" $commit)"
+          done
+        else
+          echo "Commit with the message 'Initial commit' not found."
+          exit 1
+        fi
         if [ -z "$diverged_commits" ]; then
           echo "Error: no commits to cherry-pick"
           exit 1
